// ═══════════════════════════════════════════════════════════════════════════
//  CustomCheats — Tiny INI Parser + Writer
// ═══════════════════════════════════════════════════════════════════════════

#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <stdlib.h>

#include "ini_parser.h"

// ─────────────────────────────────────────────
//  Trim helper
// ─────────────────────────────────────────────
static void trim(char *s) {
    char *p = s;
    while (*p && isspace((unsigned char)*p)) p++;
    if (p != s) memmove(s, p, strlen(p) + 1);

    size_t len = strlen(s);
    while (len > 0 && isspace((unsigned char)s[len - 1]))
        s[--len] = '\0';
}

// ─────────────────────────────────────────────
//  Parse
// ─────────────────────────────────────────────
int INI_Parse(const char *path, IniFile *out) {
    if (!path || !out) return -1;
    memset(out, 0, sizeof(*out));

    FILE *f = fopen(path, "r");
    if (!f) return -1;

    char line[512];
    char curSection[INI_MAX_SECTION] = "";

    while (fgets(line, sizeof(line), f)) {
        size_t len = strlen(line);
        while (len > 0 && (line[len-1] == '\n' || line[len-1] == '\r'))
            line[--len] = '\0';

        trim(line);
        if (line[0] == '\0' || line[0] == ';' || line[0] == '#') continue;

        if (line[0] == '[') {
            char *end = strchr(line, ']');
            if (end) {
                *end = '\0';
                strncpy(curSection, line + 1, INI_MAX_SECTION - 1);
                trim(curSection);
            }
            continue;
        }

        char *eq = strchr(line, '=');
        if (!eq) continue;
        *eq = '\0';

        char key[INI_MAX_KEY];
        char val[INI_MAX_VALUE];
        strncpy(key, line, INI_MAX_KEY - 1);
        strncpy(val, eq + 1, INI_MAX_VALUE - 1);
        trim(key);
        trim(val);

        char *semi = strchr(val, ';');
        if (semi) { *semi = '\0'; trim(val); }

        if (out->count >= INI_MAX_ENTRIES) break;

        IniEntry *e = &out->entries[out->count++];
        strncpy(e->section, curSection, INI_MAX_SECTION - 1);
        strncpy(e->key,     key,        INI_MAX_KEY     - 1);
        strncpy(e->value,   val,        INI_MAX_VALUE   - 1);
    }

    fclose(f);
    return 0;
}

// ─────────────────────────────────────────────
//  Lookup
// ─────────────────────────────────────────────
const char *INI_Get(const IniFile *ini, const char *section, const char *key) {
    if (!ini || !section || !key) return NULL;
    for (int i = 0; i < ini->count; i++) {
        const IniEntry *e = &ini->entries[i];
        if (strcasecmp(e->section, section) == 0 &&
            strcasecmp(e->key,     key)     == 0) {
            return e->value;
        }
    }
    return NULL;
}

bool INI_GetBool(const IniFile *ini, const char *section, const char *key, bool def) {
    const char *v = INI_Get(ini, section, key);
    if (!v) return def;
    return (strcasecmp(v, "true") == 0 ||
            strcasecmp(v, "yes")  == 0 ||
            strcmp(v, "1")        == 0);
}

int INI_GetInt(const IniFile *ini, const char *section, const char *key, int def) {
    const char *v = INI_Get(ini, section, key);
    if (!v) return def;
    return (int)strtol(v, NULL, 0);
}

// ─────────────────────────────────────────────
//  Writer
//
//  Minimal streaming writer: open file, write [section] headers and
//  key=value pairs in order, close.  Used to persist cheat on/off state
//  per game so toggles survive a reboot.
// ─────────────────────────────────────────────
static FILE *s_writeFile = NULL;

int INI_BeginWrite(const char *path) {
    if (s_writeFile) fclose(s_writeFile); // guard against leaked handle
    s_writeFile = fopen(path, "w");
    if (!s_writeFile) return -1;

    fprintf(s_writeFile, "; Auto-generated by CustomCheats — do not hand-edit\n\n");
    return 0;
}

int INI_WriteSection(const char *section) {
    if (!s_writeFile) return -1;
    fprintf(s_writeFile, "[%s]\n", section);
    return 0;
}

int INI_WriteBool(const char *key, bool value) {
    if (!s_writeFile) return -1;
    fprintf(s_writeFile, "%s = %s\n", key, value ? "true" : "false");
    return 0;
}

int INI_EndWrite(void) {
    if (!s_writeFile) return -1;
    fclose(s_writeFile);
    s_writeFile = NULL;
    return 0;
}
